### ISSUE TITLE
Hi I want to help you with core

### ISSUE THREAD

**Issue by PadreWoW** [MistCore/MistCore#10]
I know C++ a little and SQL
I have my own TBC server - Ghostlands.ru (OregonCore Based with my fixes)

**Comment by digz6666** [comment]
Feel free to submit fixes and patches, because its an open source project.

**Comment by PadreWoW** [comment]
Did you see this?
https://github.com/ProjectSkyfire/SkyFire_5xx

5.4.7 full support
may be you can use it here?

**Comment by Kittnz** [comment]
Well difference is that this is playable, and the skyfire 5xx isn't.
But as digz6666 said, this is a open source project. You can submit fixes and patches. I don't have too much time on working on it at the moment.

**Comment by PadreWoW** [comment]
Why?

**Comment by digz6666** [comment]
@PadreWoW What you mean by use it there? Anyway there's lots of opcode difference between 5.0.5 and 5.4.7.

**Comment by Kittnz** [comment]
Not to mention client patches..

**Comment by PadreWoW** [comment]
hmmm, but how PandaWoW working on 5.4.2?

**Comment by Kittnz** [comment]
Because this isn't the 5.4.2 version.

**Comment by PadreWoW** [comment]
Planning to update your core to 5.4.2?

**Comment by Kittnz** [comment]
Apparently i made a mistake in the team assigns. The old team can add stuff again now. Sorry about that. Website is down apparently too.

**Comment by Kittnz** [comment]
@PadreWoW No

**Comment by PadreWoW** [comment]
It can be usefull too:
https://github.com/DarkBrain2580/TrinityCore-MOP-5.1.0
https://github.com/Raknar/Pandaren5.3.0/

**Comment by Dokman** [comment]
@PadreWoW please submit bugfixes for 5.0.5 in the case that the admins want to do a 5.4.x it make a repo for it.
