### ISSUE TITLE
A lot of compile errors during build

### ISSUE THREAD

**Issue by Natureknight** [MistCore/MistCore#115]
6>........\source\src\server\game\Battlegrounds\BattlegroundMgr.cpp(1511): error C2143: syntax error : missing ',' before ':'
6>........\source\src\server\game\Battlegrounds\BattlegroundMgr.cpp(1511): error C3531: 'activeId': a symbol whose type contains 'auto' must have an initializer

Error always on 
"for (auto itr : spellMap)", or
"for (auto itr : players)", etc with "error C2143: syntax error : missing ',' before ':'"

**Comment by Natureknight** [comment]
Actually it seems is one error but at many places in the source

**Comment by UtilExe** [comment]
MistCore is not being developed actively anymore, you can therefor not expect support and similar anymore. There's only people developing and fixing it privately.

**Comment by Natureknight** [comment]
Ye, thats im trying to make, but cant compile it cuz of this error everywhere at "for (auto :" any ideas?

**Comment by caffeine239** [comment]
What compiler are you using? I'll look into this when I get home. But last time I tryed it compiled just fine

**Comment by Natureknight** [comment]
Im using Cmake 3.1.0 rc1 / MSVC 2010 Express, its so annoying :x: 
OS: Win7 x64
OpenSSL 1.0.0g

**Comment by Kittnz** [comment]
update cmake and msvc

**Comment by Natureknight** [comment]
updated msvs and now is fine, thanks !
