### ISSUE TITLE
Can Fix Lag problem?

### ISSUE THREAD

**Issue by ArashDevelop** [MistCore/MistCore#13]
Can Fix Lag problem?

the problem is very big !!!

when 100% mana no lag  but  99% or ....    Lag is Start :)  

can fix :)??

in pandashan Server Not lag :)   pls fix the source or database

**Comment by Dokman** [comment]
is the source but i don't know the lines or the codes that make the lag i need help for debug it

**Comment by Dokman** [comment]
closing this issue the same as

https://github.com/MistCore/MistCore/issues/1
