### ISSUE TITLE
[SPELL] Frost Nova error

### ISSUE THREAD

**Issue by Kittnz** [MistCore/MistCore#15]
I'v got some debug log file.
http://paste2.org/yzDY7U0V

From this log i can make out this:

```
S->C: [SMSG_TIME_SYNC_REQ 0xAA9 (2729)]
C->S: [CMSG_TIME_SYNC_RESP 0x729 (1833)]
CMSG_TIME_SYNC_RESP
Wrong time sync counter from player Testest (cheater?)
Time sync received: counter 4478826, client ticks 12, time since last sync 1
Our ticks: 48, diff 36, latency 39
S->C: [SMSG_MOVE_UPDATE 0xA6F (2671)]
S->C: [SMSG_MOVE_UPDATE 0xA6F (2671)]
C->S: [CMSG_SET_SELECTION 0x2B1 (689)]
S->C: [SMSG_UPDATE_OBJECT 0x8F7 (2295)]
C->S: [CMSG_CAST_SPELL 0x911 (2321)]
WORLD: got cast spell packet, castCount: 32, spellId: 122, castFlags: 16, data length = 46
```

CMSG_CAST_SPELL is called and send too the server. But in the end...

```
Attempted to get value with size: 50 in ByteBuffer (pos: 49 size: 4)
[Stack trace: [0x1dafa2]
[0x1d38f3]
[0x229497]
[0x229425]
[0x22d336]
[0xaf5b33]
[0xaf8369]
[0xb0471e]
[0xb059f8]
[0x3e9df9]
[0x97db6e]
[0xa3d24b]
[0xcfcaa4]
ACE_Name_Reply::ACE_Name_Reply()+0x14c6ed [0x0]
ACE_Name_Reply::ACE_Name_Reply()+0x14d8f3 [0x0]
ACE_Name_Reply::ACE_Name_Reply()+0x14d759 [0x0]
ACE_Name_Reply::ACE_Name_Reply()+0x432e0 [0x0]
beginthreadex()+0x1a1 [0x0]
endthreadex()+0x171 [0x0]
BaseThreadInitThunk()+0x12 [0x0]
RtlInitializeExceptionChain()+0x63 [0x0]
RtlInitializeExceptionChain()+0x36 [0x0]
]
WorldSession::Update ByteBufferException occured while parsing a packet (opcode: 2321) from client 127.0.0.1, accountid=2. Skipped packet.
```

In the end it gets skipped. 

If anyone can help with this. I'v been looking into the levelup functions in Player.cpp and some other functions but everything i see.. it looks logical and i don't see any errors in de the code.

Notes on how to reproduce: Make a char, pref a mage, levelup few levels (even one is ok), try use frost nova. It just get's these errors. The leveling up and updating the spells, it does something with spell casting. Other then that, everything works. You can do whatever, server doesn't hang or crash. It doesn't lag either. It is a function that disrupts the casting. 

Any help is appreciated:)

Posted also on our forum: http://www.mistcore.org/showthread.php?37-Core-Spell-cast-function-crash

Update: I have another log about this: http://paste2.org/vLgnJjH5 . This gives me more info where too look. However this only is with frost nova, packet too long?!

**Comment by ghost** [comment]
Maybe this help

https://github.com/TrinityCore/TrinityCore/commit/10c02690b607f1c1c459a8c0b4fe594bb45fe219

**Comment by Kittnz** [comment]
I doupt it, 
"Core/Units: Re-remove MOVEMENTFLAG_ROOT applying on Unit::SetRooted to fix a clientside freeze issue (our visibility system is co-reponsible). It's still an ugly hack and should be fixed properly asap."

Meaning a client bug, not a server bug.

**Comment by ghost** [comment]
use a client different from the on in dep folder, and it works

**Comment by Kittnz** [comment]
http://www.mistcore.org/showthread.php?37-Core-Frozen-Nova-Spell-cast-function-crash&p=294#post294

**Comment by Kittnz** [comment]
Fixed with new client.
