### ISSUE TITLE
npc add item (vendor)

### ISSUE THREAD

**Issue by neops8** [MistCore/MistCore#18]
commande .npc add item have a problem the command work but the item is not add ton the vendor

**Comment by Kittnz** [comment]
@neops8 What item are you trying to add?

**Comment by neops8** [comment]
all item when I do .np add item 5864 for exemple, in the chat the command appear but in the vendor there isnt any item it juste work if I do .np add item 1 1 1 
Try ingame and you will see

**Comment by UtilExe** [comment]
Confirm. I will take a look at this and try to fix it asap.

**Comment by UtilExe** [comment]
Solved -https://github.com/MistCore/MistCore/commit/595ec6b11d08f1a1be01bb09f6c4970e5ba32f54
