### ISSUE TITLE
Server crash when log out

### ISSUE THREAD

**Issue by Ruby721** [MistCore/MistCore#19]
Hi, i get new bug. When you logout your character, this will crash the server. How it looks ? Ok when you hit ESC then logout. Everythink near you will dissappear and get freezed but when you look, server crashed or is in FREEZE and can't unfreeze by itself

**Comment by Kittnz** [comment]
Compile your core in debug & post the crash log. Also tweak your log settings in the config to debug.

**Comment by Ruby721** [comment]
http://fbe.am/rn9 Here it is

**Comment by Ruby721** [comment]
Fixed this, no more help. Thanks

**Comment by Kittnz** [comment]
What was it?
