### ISSUE TITLE
Pandaren LevelUP Zone NpCes

### ISSUE THREAD

**Issue by ArashDevelop** [MistCore/MistCore#23]
hi all my problem is in map 860  pandaren levelup zone, npces  does not show 
but not fix phasmask / 

can fix it?

**Comment by 3DViking** [comment]
THe problem are coming from core.. phaseMasks must be int32..

**Comment by Kittnz** [comment]
then we have to look at it =)

**Comment by ArashDevelop** [comment]
can apply patch and pull ?

**Comment by Dokman** [comment]
when i have time i'll try to edit at push them

**Comment by 3v3rh11t** [comment]
Need write hack phase system, use this auras

SPELL_AURA_PHASE_MASK_2 = 59073
SPELL_AURA_PHASE_MASK_8 = 59087
SPELL_AURA_PHASE_MASK_1024 = 67789
SPELL_AURA_PHASE_MASK_2048 = 68480
SPELL_AURA_PHASE_MASK_4096 = 68481
SPELL_AURA_PHASE_MASK_8192 = 68482
SPELL_AURA_PHASE_MASK_16384 = 68483
SPELL_AURA_PHASE_MASK_32768 = 69077

Sorry my bad english.

**Comment by Kittnz** [comment]
Example?
