### ISSUE TITLE
Creatures don't talk

### ISSUE THREAD

**Issue by Krath** [MistCore/MistCore#28]
Hey there, I've been trying to make a NPC Talk with the following code : 
me->MonsterSay("Bla bla bla", LANG_UNIVERSAL, me->GetGUID());
 but it doesn't seem to work. What's the problem?

**Comment by ghost** [comment]
there's a lot of issues related to creature texts, we are working on it

**Comment by FALL1N1** [comment]
try without me->GetGUID()

**Comment by Krath** [comment]
Still not working without GetGuid. I tried everything. Even Yell isn't working

**Comment by caffeine239** [comment]
odd this is a true statement :(

**Comment by caffeine239** [comment]
Fixed in https://github.com/MistCore/MistCore/commit/f817046c04fd9e0c32d44566626338b5a563c0ff
