### ISSUE TITLE
/Zm  Change

### ISSUE THREAD

**Issue by ArashDevelop** [MistCore/MistCore#3]
cmake\compiler\msvc\settings.cmake  CHANGE IT   , Change For Worked On Lower Ram Pces

in line 57

string(REGEX REPLACE "/Zm[0-9]+ *" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm2000" CACHE STRING "" FORCE)

Replace To:

string(REGEX REPLACE "/Zm[0-9]+ *" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm500" CACHE STRING "" FORCE)

**Comment by digz6666** [comment]
It fixes the compile issue on visual studio 2010 and older. Anyway its compiling fine on visual studio 2013.

**Comment by Dokman** [comment]
but it can be useful i think XD a lot of people i don't know why uses vs 10

**Comment by Dokman** [comment]
https://github.com/MistCore/MistCore/commit/2df525c9c0367745bece85c21951d1950b8282b0

**Comment by Dokman** [comment]
lowered ram

**Comment by Kittnz** [comment]
Fine by me
