### ISSUE TITLE
When 30+ players server lag

### ISSUE THREAD

**Issue by Ruby721** [MistCore/MistCore#34]
Hi there, there is a another problem. When  I Have 30+ players it lags when you logging in with character or logging out with character. Do you know how to fix that ? If you know, i can release my script to fix losing items, logout crash and more and more. Thanks !

**Comment by FALL1N1** [comment]
Release them and i'll help you.

**Comment by Ruby721** [comment]
add me on skype ruby-mds

**Comment by ghost** [comment]
you have a bad mysql config, our maybe your machine is not good enough, or maybe your connection is not the best. i have over 200 in one realm and doesnt lag or crash at all.

**Comment by Kittnz** [comment]
Yes i heard from people who are running 5.0.5 that it works pretty well. Only a few issues. We would appriciate it too if you could contribute so the project gets better.

**Comment by Ruby721** [comment]
Which Mysql server Version you using ?

**Comment by FALL1N1** [comment]
#1
