### ISSUE TITLE
MySQL server crash.

### ISSUE THREAD

**Issue by Ruby721** [MistCore/MistCore#35]
Using MySQL server 5.1
MySQL crashed IDK when. But when it crashed. No one can't connect to world.
They Will stuck on Loadin screen for hours.
Here is Crash Report.
Does have any one some ideas how to fix that ? 

http://pastebin.com/mVtCWRLz

**Comment by Kittnz** [comment]
Are you using the right libmysql.dll? The one that gets compiled with this core?
I see this: C:\tcofficial\bin\RelWithDebInfo\libmysql.dll
While the rest is in c:\trinitycoremop\

**Comment by Ruby721** [comment]
I recompiled this with right source. I ll write about if it crash again.

**Comment by Ruby721** [comment]
No still the same problem. After 1 Hour.
http://pastebin.com/VgiGb3Bb

**Comment by Kittnz** [comment]
Did you do any modifications to the core/database? what does the log output say?

**Comment by Ruby721** [comment]
No Modifications. and which log ? Where i can find him ?

**Comment by Kittnz** [comment]
DBErrors, server log.. you can always adjust your logging config to be more precise. Maybe you can find something in LOGGING SYSTEM SETTINGS in worldserver.conf. Debug.

**Comment by Ruby721** [comment]
http://fbe.am/rVT Here it is.
Config Here : http://pastebin.com/wj5xaUkY

**Comment by Ruby721** [comment]
This is not working.. and still crashing

**Comment by Ruby721** [comment]
http://pastebin.com/6PiquZ37 still crashing after 2 hrs.

**Comment by Ruby721** [comment]
I fixed this. Mistcore support really sucks...

**Comment by Kittnz** [comment]
@Ruby721 problem is that we don't have enough people working on it, i didn't have much time to look into it. Maybe you could share what was wrong? Bad mysql version?

**Comment by Ruby721** [comment]
Not version. Remove the fucking pandashan firewall

**Comment by FALL1N1** [comment]
Op firewall blocking connections/players.
