### ISSUE TITLE
Frame rates 

### ISSUE THREAD

**Issue by Kalmageddon** [MistCore/MistCore#36]
When ever I cast  a spell that has a cost, either mana, energy, etc, it breaks down my fps from 60's to 1-10 fps and its really annoying. I've seen someone else posting an issue about this but that issue is closed, but It doesnt seem to be fixed, Im not the only one with this problem, but there are other that dont experience this issue aswell, so I cant really be sure what the problem is.

If possible please take a look at it, its really impossible to play with less that 8 fps while in dungeons/raids/bgs...

**Comment by Kalmageddon** [comment]
Here's a pic with me auto attacking (While in combat of course) and not having this issue while at full mana:
http://i.imgur.com/FIcaUeW.jpg

Here's another print with me without being full mana and in combat, which you can notice the FPS drop:
http://i.imgur.com/09tqNS0.jpg

**Comment by FALL1N1** [comment]
Buy new pc.

**Comment by Kalmageddon** [comment]
Yea, thats a great insight on this issue, thanks.
I'll wait for more worthy people who want this feedback. You asked for feedback and I'm giving it to you.

**Comment by FALL1N1** [comment]
Why it doesnt do this on my realm? Because im not running it on 2gb ram, core2duo 1.8ghz and crap hdd.

**Comment by Kalmageddon** [comment]
I got 4gigs of ram, 2.4ghz processor and a 7200rpm hdd. I'm good to play this game on "good", taking shadows off. 
Its not happening to everyone as I said, a few players experience this issue. 
Also, I play on pandashan aswell and I got no issues with this. 
Now leave this issue to someone who wants to check this up and stop picking on me about my hardware. Have a great day.

**Comment by Kittnz** [comment]
GFX? Running and playing on the same machine?

**Comment by Dokman** [comment]
it's normal if you use this specs XD you need 2 GB of ram or more for use the emulator and client it need's like 1 GB more and the OS it need'slike 1,5 GB youdon't have enough memory

**Comment by Kalmageddon** [comment]
Im not emulating the server, so no, not playing on the same machine as the server... 

I have 4 gigs of ram, stop telling me its not enough to run wow, even tho my graphics is a 256mb one, its good enough for wow on good to fair settings taking off a few more demanding settings like shadows and so on.
And I'll remind you again, I can play fine on pandashan servers (got another wow folder for 5.4, and I used to play when they were 5.0.5 just FINE).

**Comment by Kittnz** [comment]
Hey, keep it calm here, we don't know how good you computer is. So you are having 1 machine for the server and one to play on? Thing is the rest of us doesn't have any issue like this.

**Comment by Kalmageddon** [comment]
The server isnt mine per say... Im just a player. Well, like I told you, a few of us on that server get this issue, but a very little part of the people. Its still worth to report and thats what I did. 

If its useless, delete this and when someone else some time later reports anything of the sort, I guess you'll remember this report.

Thanks and keep it good.

**Comment by Kalmageddon** [comment]
PS: someone else referred to having "lag" when below 100% mana but what I guess he meant was that he was having fps lag... Issue #6

**Comment by Mentala** [comment]
Kalma nothing personal, but ITS WAY DIFFERENT to play on Pandashan or no matter where and to hold a server on a ordinary PC and while hosting it to play in it. I had the same issue, but I've noticed that the problem was from me - re-installed my windows, because it was full with crap. And no matter if you can run WoW on good, fair, high, ultra it's way different from ordinary PC to a SERVER machine. Cheers hope you understand.

**Comment by Kalmageddon** [comment]
Hey, thanks for the reply, but I'm not playing with the same machine as the machine that hosts the server, the server has its own dedicated server machine.
My windows isnt a problem, I have a habit of formatting my computer each 4-6 months to keep it smooth, so yeah...

**Comment by ghost** [comment]
there's actually an issue on the 2nd boss of Mogushan Vaults where fps run low globally, and the server is mine btw.

**Comment by caffeine239** [comment]
this should also be solved with https://github.com/MistCore/MistCore/commit/02bf6e3df2d99533b47bbe1dd4121f82197fefaa
and https://github.com/MistCore/MistCore/commit/f758224dc54ec8af6531a9f2f1155e912ce2ccb0
