### ISSUE TITLE
Warrior & Rogue talents

### ISSUE THREAD

**Issue by Mentala** [MistCore/MistCore#37]
The warrior's Double time http://www.wowhead.com/spell=103827
does not set on Charge the "2" charges

The rogue's Subterfuge http://www.wowhead.com/spell=115192 
when you learn it and click on stealth it only shares cooldown, but you can't stealth

The hunter's Aimed Shot does enormous damage I tried to fix it through SQL in spell_bonus and the other spell tables, but no success.

**Comment by Ruby721** [comment]
try to fix it in rogue spell .cpp and warrior. I ll look for this, and maybe can help you with that.

**Comment by Mentala** [comment]
Ok thank you, I'll try too, if something happens I'll post it.

**Comment by Kittnz** [comment]
Fixes Lava Surge and Warrior Talent Double Time 
https://github.com/MistCore/MistCore/commit/b8ced0d6e474fe9730f433d3d0c0555540630601
& 
Final Fix for Subterfuge (Rogue Talent) 
https://github.com/MistCore/MistCore/commit/39d2949f10c772d03255bc68042b488d67bb8a68
