### ISSUE TITLE
problem on the encounter spirit kings

### ISSUE THREAD

**Issue by barrotes** [MistCore/MistCore#39]
the issue is that the lorewalker doesent start the event thats begins the sumoning of the bosses http://www.wowhead.com/search?q=spirit+kings which is he walks around start spawning mobs and then it spawns the bosses does annyone has a fix for the encounter

**Comment by ghost** [comment]
Closed on : https://github.com/MistCore/MistCore/commit/9164b81d1673e578c11e06d693fa7c599a182add
