### ISSUE TITLE
Dungeons Ring,Trinket error 

### ISSUE THREAD

**Issue by Gonzywow** [MistCore/MistCore#4]
The error can not add gm command Trinket, Ring, which is the dungeons, he writes, "This item Can not be equipped," can not create item "86321" (amunt1) can not put it into the bag.

who can help me

**Comment by digz6666** [comment]
Can you post a screenshot?

**Comment by Gonzywow** [comment]
http://kepfeltoltes.hu/view/140216/WoWScrnShot_021614_124537_www.kepfeltoltes.hu_.jpg

**Comment by jacobmain1** [comment]
any news ?

**Comment by digz6666** [comment]
@Gonzywow Cannot see the screenshots, can you upload to tinypic.com?

**Comment by Gonzywow** [comment]
http://i60.tinypic.com/8vrldu.jpg

**Comment by Yamatoo** [comment]
any news?

**Comment by jacobmain1** [comment]
any news ? big problem..

**Comment by Farbod** [comment]
Any news ?

**Comment by Dokman** [comment]
yes simply doesn't have an entry it says that have a 0 entry search for it in item_template if exist we have to see the code, cause is a hackfix and an invalid id
