### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Mentala** [MistCore/MistCore#45]
They are a few error that you caný compile as I saw them were:
A few in elwynforest.cpp
npc_glubtog.cpp
in worldsocket.cpp and then no wolrdserver.exe in the folder

**Comment by Basti420** [comment]
Update to this commit and it will work again https://github.com/MistCore/MistCore/commit/749993a5d1ece32b371d58b9c7a28c1e1ccf5049

**Comment by Mentala** [comment]
It worked thanks for the fast feedback.
