### ISSUE TITLE
Debian Compiling Error

### ISSUE THREAD

**Issue by Orangs** [MistCore/MistCore#51]
im trying to compile our Emulator on my Debian server but i have problem. Im clone newest repo and trying to compile, but this error come to my console.

[ 12%] Building CXX object src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatScripts.cpp.o
In file included from /home/wowko/mop/MistCore/src/server/game/Grids/Notifiers/GridNotifiers.h:33,
                 from /home/wowko/mop/MistCore/src/server/scripts/PrecompiledHeaders/ScriptPCH.h:12,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.h:4,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.cpp:1:
/home/wowko/mop/MistCore/src/server/game/AI/CreatureAI.h:153: warning: unused parameter 'power'
/home/wowko/mop/MistCore/src/server/game/AI/CreatureAI.h:153: warning: unused parameter 'value'
In file included from /home/wowko/mop/MistCore/src/server/scripts/PrecompiledHeaders/ScriptPCH.h:12,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.h:4,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.cpp:1:
/home/wowko/mop/MistCore/src/server/game/Grids/Notifiers/GridNotifiers.h: In constructor 'MistCore::AnyUnitHavingBuffInObjectRangeCheck::AnyUnitHavingBuffInObjectRangeCheck(const WorldObject_, const Unit_, float, uint32, bool)':
/home/wowko/mop/MistCore/src/server/game/Grids/Notifiers/GridNotifiers.h:917: warning: 'MistCore::AnyUnitHavingBuffInObjectRangeCheck::i_spellid' will be initialized after
/home/wowko/mop/MistCore/src/server/game/Grids/Notifiers/GridNotifiers.h:916: warning:   'bool MistCore::AnyUnitHavingBuffInObjectRangeCheck::i_friendly'
/home/wowko/mop/MistCore/src/server/game/Grids/Notifiers/GridNotifiers.h:903: warning:   when initialized here
In file included from /home/wowko/mop/MistCore/src/server/scripts/PrecompiledHeaders/ScriptPCH.h:25,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.h:4,
                 from /home/wowko/mop/MistCore/src/server/game/Anticheat/AnticheatScripts.cpp:1:
/home/wowko/mop/MistCore/src/server/game/Spells/SpellScript.h: In constructor 'AuraScript::AuraScript()':
/home/wowko/mop/MistCore/src/server/game/Spells/SpellScript.h:619: error: no matching function for call to 'std::shared_ptr<Aura>::shared_ptr(NULL)'
compilation terminated due to -Wfatal-errors.
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatScripts.cpp.o] Error 1
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
make: **\* [all] Error 2

Its some wrong in Script or in cmake or where? :/ Im confused..

**Comment by Dude100** [comment]
uname -a ?

**Comment by Orangs** [comment]
Linux cataclysm 2.6.32-042stab084.20 #1 SMP Mon Jan 27 00:40:08 MSK 2014 x86_64 GNU/Linux

**Comment by Orangs** [comment]
Anyone know how to fix this error?

**Comment by Dude100** [comment]
try to upgrade Debian stable releas this kernel is old stable squeeze stable is wheezy kernel version Linux kernel 3.2 just apt-get update apt-get dist-upgrade

**Comment by Dude100** [comment]
try first apt-get update

**Comment by Orangs** [comment]
It works! Thanks for help DrFyckme

**Comment by Dude100** [comment]
cmake  ../ -DPREFIX=/home/urdir/Mistcore -DTOOLS=1

**Comment by Dude100** [comment]
and see here http://www.mistcore.org/forumdisplay.php?9-Tools-Development

**Comment by Orangs** [comment]
Reopen! First compile is works, but other compiles still give this error! :/.....
After the update, i have still Linux cataclysm 2.6.32-042stab084.20 #1 SMP Mon Jan 27 00:40:08 MSK 2014 x86_64 GNU/Linux
Now im totally confused....

**Comment by Dude100** [comment]
oh give skype

**Comment by Orangs** [comment]
zalman-cze

**Comment by Kittnz** [comment]
I'm trying to follow here what's going on but i must admit i have no clue about linux :(

**Comment by Dude100** [comment]
Old version DEbian and gcc.. next Debian upgrade steb by step :)

**Comment by Kittnz** [comment]
Well atleast someone knows the know how, so that's good. Glad atleast someone can help!
