### ISSUE TITLE
Cannot Share Quests

### ISSUE THREAD

**Issue by ghost** [MistCore/MistCore#52]
Is not possible to share quests (latest rev)

i'm opening tickets just to keep it in track

**Comment by caffeine239** [comment]
Comfired. Working on this next

**Comment by caffeine239** [comment]
About 50% working now

**Comment by Kittnz** [comment]
Lol how does that happen? What did you do?

**Comment by caffeine239** [comment]
packet structures are wrong

**Comment by caffeine239** [comment]
Fixed in https://github.com/MistCore/MistCore/commit/0a60693376b31b0e79548731fbce65fadf775af5
