### ISSUE TITLE
Cannot use /roll

### ISSUE THREAD

**Issue by ghost** [MistCore/MistCore#53]
/roll command is not available , no output on chat

**Comment by Kittnz** [comment]
If i'm not mistaken, i think we need to update opcode and structure.

**Comment by FALL1N1** [comment]
structure only

**Comment by soulfrost** [comment]
no. ocode too.

**Comment by caffeine239** [comment]
Actually opcode is half right i think

**Comment by caffeine239** [comment]
actually missing more than what u think :) http://oi60.tinypic.com/14916rq.jpg

**Comment by FALL1N1** [comment]
I can make screenshot of my fix too, that doesnt prove anything. Push it or stop being a dick :P
Tell me when you fix this: http://i.imgur.com/zE019Lz.jpg thanks to @Zhelyazkov

**Comment by soulfrost** [comment]
@caffeine239 allready fixed - i send fix to @Kittnz - he'll push it

**Comment by caffeine239** [comment]
@JunkyBulgaria your a Collaborator and have a fix and didnt push it? geezz what a great team

**Comment by Kittnz** [comment]
https://github.com/MistCore/MistCore/commit/772ef73ea803a57fb857d8eee7f2a91549a2aa9e
