### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by ghost** [MistCore/MistCore#58]
Guys I'm with some compilation errors. 
Even downloading the source again I get errors.

Screenshot:
http://oi59.tinypic.com/f8086.jpg

**Comment by Kittnz** [comment]
Ill look at it tonight

**Comment by FALL1N1** [comment]
replace GetTarget with getTarget || remove the break; line

**Comment by ghost** [comment]
Now the error is about getTarget in this line

uint64 selected = m_session->GetPlayer()->getTarget();
