### ISSUE TITLE
Server LAG problem - /roll & Sell item

### ISSUE THREAD

**Issue by Farbod** [MistCore/MistCore#6]
Guys
I found that when you have 100% mana you won't get lag , but when your character has 1-99% mana you will get lag 100% lag.

/roll dosen't work
you won't sell items to npc

**Comment by FALL1N1** [comment]
Remove pandashan's code for opcode flood.

**Comment by FALL1N1** [comment]
I'm not medium.

**Comment by Farbod** [comment]
Dear where is opcode flood ? could you tell me ?

**Comment by Dokman** [comment]
can you help us telling the opcodes and making pull requests? @JunkyBulgaria

**Comment by FALL1N1** [comment]
/roll has missing opcode & wrong structure, you can sniff it from http://pandawow.ru/

**Comment by Kalmageddon** [comment]
I can confirm that if you're at 100% mana you get no FPS lag at all and if you cast a spell that costs mana and takes you below 100% mana, you start to have FPS lag.
#36

**Comment by FALL1N1** [comment]
Δ
 |
Reinstall windows.

**Comment by FALL1N1** [comment]
#1

**Comment by soulfrost** [comment]
@JunkyBulgaria u are retaed... dont delete comment with code, and dont make shit posts if u dont know why people get problems

**Comment by FALL1N1** [comment]
I haven't deleted anything? Also commits cant be deleted, they can be reverted/reset. I'm linking all the issues together in one with more information. The problem is comming from the hack for mana regen in Player.cpp and OBJECT_UPDATE system being flooded by SERVER->CLIENT which takes 5-6mbps on spell cast, mana regen and any other C>S communication.

**Comment by soulfrost** [comment]
i send 2 hours ago comment with : http://take.ms/wyFBd
it's hack fix for problem -  another way not finded yet

**Comment by Kittnz** [comment]
Didn't see anything removed, thanks for the fix tho

**Comment by soulfrost** [comment]
if u want - add me in skype: heyseypro - i can help with fix some hard problems
