### ISSUE TITLE
challenge mode

### ISSUE THREAD

**Issue by Basti420** [MistCore/MistCore#65]
challenge mode does not work, you cant select the challenge mode difficulty

**Comment by Kittnz** [comment]
Not implemented, need sniffs and such.

**Comment by Farbod** [comment]
Here to sniff , contact me

**Comment by FALL1N1** [comment]
Im just curious.. where are you going to sniff it from since blizz is on 5.4?

**Comment by caffeine239** [comment]
i always say.. fucka sniff

**Comment by caffeine239** [comment]
fixed https://github.com/MistCore/MistCore/commit/90fad72114a5918c06d64eff7ec45cc139dfb2d0 Closing until mode is actually tested

**Comment by Farbod** [comment]
maybe pandawow.ru
