### ISSUE TITLE
Linux Tools Build

### ISSUE THREAD

**Issue by Basti420** [MistCore/MistCore#69]
/usr/bin/ld: ../../server/collision/libcollision.a(TileAssembler.cpp.o): undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [src/tools/vmap4_assembler/vmap4assembler] Fehler 1
make[1]: **\* [src/tools/vmap4_assembler/CMakeFiles/vmap4assembler.dir/all] Fehler 2
make[1]: **\* Warte auf noch nicht beendete Prozesse...
[ 46%] Built target game
[100%] Built target scripts
make: **\* [all] Fehler 2

cant build tools on linux

**Comment by Dude100** [comment]
confirm

**Comment by Kittnz** [comment]
I don't have any exp in linux sadly enough. If anyone with linux exp can help, would be cool.

**Comment by Basti420** [comment]
fixed pthread wasn't linked
