### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Syloxus** [MistCore/MistCore#86]
Latency always seems to be 0ms, even when it's running from another location

**Comment by ghost** [comment]
client issue.

**Comment by zzhel** [comment]
Not at all, it's a wrong cmsg structure

**Comment by ghost** [comment]
it is? i thought it was patched client issue, because with other i didnt had that issue.

**Comment by Dokman** [comment]
did you have another client? @silvermcd123

**Comment by soulfrost** [comment]
it's packet issue. give me sniffs of this opcodes ( smsg / cmsg ) i dont have time to sniff it self

**Comment by caffeine239** [comment]
im gonna agree patched client issue...

**Comment by caffeine239** [comment]
@Zhelyazkov and your a Collaborator push the fix...

**Comment by Kittnz** [comment]
I think he has but he doesn't want too share it because he is selling his fixes on ac-web.
