### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by Basti420** [MistCore/MistCore#88]
Scanning dependencies of target shared
[  0%] Built target gsoap
[  2%] Built target jemalloc
-- WARNING - Missing repository tags - you may need to pull tags with git fetch -t
-- WARNING - Continuing anyway - note that the versionstring will be set to 0000-00-00 00:00:00 (Archived)
Scanning dependencies of target collision
[  2%] Built target revision.h
[  6%] Built target g3dlib
Scanning dependencies of target game
Scanning dependencies of target scripts
[  6%] [  6%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Management/VMapFactory.cpp.o
Building CXX object src/server/collision/CMakeFiles/collision.dir/Management/VMapManager2.cpp.o
[  6%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/BigNumber.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/Authentication/AuthCrypt.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/ARC4.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/SHA1.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Cryptography/HMACSHA1.cpp.o
[  7%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Maps/MapTree.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/Field.cpp.o
[  7%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Maps/TileAssembler.cpp.o
[  7%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/DatabaseWorker.cpp.o
[  8%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Models/GameObjectModel.cpp.o
[  8%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/AdhocStatement.cpp.o
[  8%] Building CXX object src/server/game/CMakeFiles/game.dir/Accounts/AccountMgr.cpp.o
[  8%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/PreparedStatement.cpp.o
[  8%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Models/ModelInstance.cpp.o
[  8%] Building CXX object src/server/collision/CMakeFiles/collision.dir/Models/WorldModel.cpp.o
[  8%] Building CXX object src/server/collision/CMakeFiles/collision.dir/DynamicTree.cpp.o
[  8%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/Implementation/CharacterDatabase.cpp.o
[  9%] Building CXX object src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatData.cpp.o
[  9%] Building CXX object src/server/collision/CMakeFiles/collision.dir/BoundingIntervalHierarchy.cpp.o
[  9%] Building CXX object src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatMgr.cpp.o
Linking CXX static library libcollision.a
[  9%] Built target collision
[  9%] Building CXX object src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatScripts.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/Implementation/LoginDatabase.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/Implementation/WorldDatabase.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/QueryHolder.cpp.o
[ 10%] Building CXX object src/server/game/CMakeFiles/game.dir/Achievements/AchievementMgr.cpp.o
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/shared/Database/QueryHolder.cpp: In member function ‘bool SQLQueryHolder::SetPQuery(size_t, const char_, ...)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/shared/Database/QueryHolder.cpp:47:76: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
         sLog->outError(LOG_FILTER_SQL, "Query (index: %u) is empty.", index);
                                                                            ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/shared/Database/QueryHolder.cpp: In member function ‘bool SQLQueryHolder::SetPreparedQuery(size_t, PreparedStatement_)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/shared/Database/QueryHolder.cpp:70:138: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
         sLog->outError(LOG_FILTER_SQL, "Query index (%u) out of range (size: %u) for prepared statement", index, (uint32)m_queries.size());
                                                                                                                                          ^
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/Transaction.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/QueryResult.cpp.o
[ 10%] Building CXX object src/server/game/CMakeFiles/game.dir/Addons/AddonMgr.cpp.o
[ 10%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAI.cpp.o
[ 10%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Database/MySQLConnection.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/DataStores/DBCFileLoader.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/DataStores/DB2FileLoader.cpp.o
[ 10%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/Appender.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/LogOperation.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/Log.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/AppenderConsole.cpp.o
[ 11%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/ScriptedAI/ScriptedCreature.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/LogWorker.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/AppenderDB.cpp.o
[ 11%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_hunter.cpp.o
[ 11%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/AppenderFile.cpp.o
[ 12%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_rogue.cpp.o
[ 12%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_druid.cpp.o
[ 12%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Logging/Logger.cpp.o
[ 12%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Threading/Threading.cpp.o
[ 12%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Threading/DelayExecutor.cpp.o
[ 12%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Utilities/Util.cpp.o
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp: In member function ‘void spell_rog_shroud_of_concealment::spell_rog_shroud_of_concealment_SpellScript::SelectTargets(std::list<WorldObject*>&)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:866:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_WS_SPELL_WARSONG_FLAG));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:867:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_WS_SPELL_SILVERWING_FLAG));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:868:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_1));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:869:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_2));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:870:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_3));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:871:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_4));
                                   ^
[ 12%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/ScriptedAI/ScriptedEscortAI.cpp.o
[ 13%] make[2]: **\* [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_rogue.cpp.o] Fehler 1
make[2]: **\* Warte auf noch nicht beendete Prozesse...
Building CXX object src/server/shared/CMakeFiles/shared.dir/Utilities/ServiceWin32.cpp.o
[ 13%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Utilities/EventProcessor.cpp.o
[ 13%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/ScriptedAI/ScriptedFollowerAI.cpp.o
[ 13%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Common.cpp.o
Linking CXX static library libshared.a
[ 13%] Built target shared
Scanning dependencies of target authserver
[ 13%] Building CXX object src/server/authserver/CMakeFiles/authserver.dir/Authentication/AuthCodes.cpp.o
[ 13%] Building CXX object src/server/authserver/CMakeFiles/authserver.dir/Realms/RealmList.cpp.o
[ 13%] Building CXX object src/server/authserver/CMakeFiles/authserver.dir/Server/AuthSocket.cpp.o
[ 13%] Building CXX object src/server/authserver/CMakeFiles/authserver.dir/Server/RealmSocket.cpp.o
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Fehler 2
make[1]: **\* Warte auf noch nicht beendete Prozesse...
[ 13%] Building CXX object src/server/authserver/CMakeFiles/authserver.dir/Main.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/ReactorAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/CombatAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/TotemAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/GameObjectAI.cpp.o
Linking CXX executable authserver
[ 14%] Built target authserver
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/UnitAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/PetAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/PassiveAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/GuardAI.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o
[ 14%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartAI.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartScript.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartScriptMgr.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/AuctionHouse/AuctionHouseMgr.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlefield/Battlefield.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlefield/BattlefieldMgr.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlefield/Zones/BattlefieldWG.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlefield/BattlefieldHandler.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/ArenaTeam.cpp.o
[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/ArenaTeamMgr.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundMgr.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundRB.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundBE.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundSA.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundSSM.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundAB.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundRL.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundBFG.cpp.o
[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundRV.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundWS.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundAA.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundEY.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundTP.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundAV.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundDS.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundIC.cpp.o
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundTP.cpp: In member function ‘virtual void BattlegroundTP::PostUpdateImpl(uint32)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundTP.cpp:72:41: warning: passing NULL to non-pointer argument 1 of ‘void BattlegroundTP::EndBattleground(uint32)’ [-Wconversion-null]
                     EndBattleground(NULL);
                                         ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp: In destructor ‘virtual BattlegroundIC::~BattlegroundIC()’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp:60:5: error: ‘sMapMgr’ was not declared in this scope
     sMapMgr->m_Transports.erase(gunshipHorde);
     ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp: In member function ‘Transport\* BattlegroundIC::CreateTransport(uint32, uint32)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp:971:5: error: ‘sMapMgr’ was not declared in this scope
     sMapMgr->m_Transports.insert(t);
     ^
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundNA.cpp.o
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundKT.cpp.o
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundIC.cpp.o] Fehler 1
make[2]: **\* Warte auf noch nicht beendete Prozesse...
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Fehler 2
make: **\* [all] Fehler 2
sebastian@sebastian-GA-78LMT-S2P ~/Schreibtisch/World of Warcraft Emulation/MistCore/build $ make -j5
[  0%] Built target gsoap
[  2%] Built target jemalloc
-- WARNING - Missing repository tags - you may need to pull tags with git fetch -t
-- WARNING - Continuing anyway - note that the versionstring will be set to 0000-00-00 00:00:00 (Archived)
[  2%] Built target revision.h
[  6%] Built target g3dlib
[  7%] Built target collision
[ 11%] Built target shared
[ 11%] Built target authserver
[ 11%] [ 12%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundIC.cpp.o
[ 12%] [ 12%] Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/BattlegroundQueue.cpp.o
Building CXX object src/server/game/CMakeFiles/game.dir/BattlePet/BattlePetMgr.cpp.o
Building CXX object src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp: In destructor ‘virtual BattlegroundIC::~BattlegroundIC()’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp:60:5: error: ‘sMapMgr’ was not declared in this scope
     sMapMgr->m_Transports.erase(gunshipHorde);
     ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp: In member function ‘Transport\* BattlegroundIC::CreateTransport(uint32, uint32)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/game/Battlegrounds/Zones/BattlegroundIC.cpp:971:5: error: ‘sMapMgr’ was not declared in this scope
     sMapMgr->m_Transports.insert(t);
     ^
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Zones/BattlegroundIC.cpp.o] Fehler 1
make[2]: **\* Warte auf noch nicht beendete Prozesse...
[ 13%] [ 13%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_rogue.cpp.o
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_dk.cpp.o
[ 13%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_quest.cpp.o
[ 13%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_warrior.cpp.o
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Fehler 2
make[1]: **\* Warte auf noch nicht beendete Prozesse...
[ 13%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_generic.cpp.o
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp: In member function ‘void spell_rog_shroud_of_concealment::spell_rog_shroud_of_concealment_SpellScript::SelectTargets(std::list<WorldObject*>&)’:
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:866:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_WS_SPELL_WARSONG_FLAG));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:867:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_WS_SPELL_SILVERWING_FLAG));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:868:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_1));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:869:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_2));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:870:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_3));
                                   ^
/home/sebastian/Schreibtisch/World of Warcraft Emulation/MistCore/src/server/scripts/Spells/spell_rogue.cpp:871:35: error: ‘UnitAuraCheck’ is not a member of ‘MistCore’
                 targets.remove_if(MistCore::UnitAuraCheck(true, BG_KT_SPELL_ORB_PICKED_UP_4));
                                   ^
make[2]: **\* [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_rogue.cpp.o] Fehler 1
make[2]: **\* Warte auf noch nicht beendete Prozesse...
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Fehler 2
make: **\* [all] Fehler 2

**Comment by Basti420** [comment]
seems to be broken since the ace update i think :( don't know how to fix this

**Comment by Kittnz** [comment]
Use the old ace one. It's in the "dep/ace_". i left it there just in case.

**Comment by Dude100** [comment]
what linux use so please if you report Linux Build first use uname -a and gcc --version

**Comment by Basti420** [comment]
Linux sebastian-GA-78LMT-S2P 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

gcc (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1

works fine again with the old ace

**Comment by Dude100** [comment]
try downgrade yr gcc use this version root@debian:~# gcc --version
gcc (Debian 4.7.3-11) 4.7.3

**Comment by Dude100** [comment]
use this script: 
http://pastebin.com/T5kr0h0m

**Comment by Basti420** [comment]
now it works thanks

**Comment by Dude100** [comment]
np :)
