### ISSUE TITLE
Core/Player: UpdateSkillPro

### ISSUE THREAD

**Issue by antiker** [MistCore/MistCore#9]
Change in Player.cpp

static uint32 bonusSkillLevels[] = {75, 150, 225, 300, 375, 450};
to
static uint32 bonusSkillLevels[] = { 75, 150, 225, 300, 375, 450, 525, 600 };

**Comment by Kittnz** [comment]
Make a pull request please.

**Comment by Kittnz** [comment]
I am guessing this is for the professions? Ill look at tonight. Thanks!

**Comment by Dokman** [comment]
thx for the patch you can make a fork and like @Kittnz says you can make pull request feel free to make them

**Comment by Kittnz** [comment]
#12
