### ISSUE TITLE
Rogue Fan of Knives, Crimson Tempest

### ISSUE THREAD

**Issue by Epicurus4** [MistCore/MistCore#99]
Commit: e6b4fefc8a01228c8fabe55488297e95b2beb2f7
Rogue Fan of Knives: http://www.wowhead.com/spell=51723
Rogue Crimson Tempest: http://www.wowhead.com/spell=121411

Both Fan of Knives and Crimson Tempest don't do anything after being used. The worldserver logs the following after using either ability:

Attempted to get value with size: 47 in ByteBuffer (pos: 46 size: 4)
[Stack trace: ./worldserver(_ZN12WorldSession21HandleMovementOpcodesER11WorldPacket+0x1ee) [0xc0fc4e]
./worldserver(_ZN12WorldSession21HandleClientCastFlagsER11WorldPackethR16SpellCastTargets+0x4b8) [0xe68968]
./worldserver(_ZN12WorldSession21HandleCastSpellOpcodeER11WorldPacket+0x4a9) [0xe6c2c9]
./worldserver(_ZN12WorldSession6UpdateEjR12PacketFilter+0x481) [0xc9b681]
./worldserver(_ZN3Map6UpdateEj+0x87) [0xc45b17]
./worldserver(_ZN16MapUpdateRequest4callEv+0x11) [0xe84db1]
./worldserver(_ZN13DelayExecutor3svcEv+0x31) [0xf0f061]
/usr/local/lib/libACE-6.0.3.so(_ZN13ACE_Task_Base7svc_runEPv+0x37) [0x7f423d2d0977]
/usr/local/lib/libACE-6.0.3.so(_ZN18ACE_Thread_Adapter8invoke_iEv+0x75) [0x7f423d2d1fe5]
/usr/local/lib/libACE-6.0.3.so(_ZN18ACE_Thread_Adapter6invokeEv+0x5f) [0x7f423d2d1f2f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7f6e) [0x7f423bc2ef6e]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f423b9599cd]
]
WorldSession::Update ByteBufferException occured while parsing a packet (opcode: 2321) from client 127.0.0.1, accountid=1. Skipped packet.

Epicurus

**Comment by FALL1N1** [comment]
Try new client.

**Comment by Epicurus4** [comment]
Junky, what client are you using?

Can anyone else verify that it is indeed a client issue? I've tried multiple clients, including my own Blizzard install of 505 enUS, 505 clients from private servers and loaded MPQs from this list:
http://dl.dropboxusercontent.com/u/86702979/Data/enUS_index.html

The issue is the same. This core is pretty dated. It's possible that it's not handling the incoming bytes correctly.

**Comment by jack6969** [comment]
Both spells are working Right with the Launcher Included with the core

**Comment by Epicurus4** [comment]
Thanks Jack, I was not aware of a launcher packaged with the core. I was manually patching my clients.

I'm currently in the process of debugging my core. As soon as I get it running again I'll try with the packaged launcher. If all is well, I'll close this issue.

**Comment by jack6969** [comment]
your welcome m8 I did Test the spells to be sure they were working ! so if you use the Launcher Packaged with the core every thing seems to work ok

**Comment by Epicurus4** [comment]
Indeed all is well using the launcher in the package. Thanks again, Jack.

**Comment by caffeine239** [comment]
shitty patch job of client pandashan! shame on you

**Comment by FALL1N1** [comment]
just to mention that this core is 1yr old from pandashan's 5.0.5

**Comment by Kittnz** [comment]
Everything changes, specially with people and budget and a lot of free time.

**Comment by Kittnz** [comment]
Not to mention this is exactly why it's best to share what we already have made for this core.

**Comment by Epicurus4** [comment]
Yes Kittnz, I'm with you there. I've been trying to get the Core up to date with the latest TrinityCore, but it's proving to be more difficult that I had initially anticipated. So much has changed in the past 2 years (BloodCore, the pandashan leak, is based on TrinityCore 2012).

If I had a legacy version of TrinityCore, preferably the same build used by BloodCore, it would be so much easier to isolate what Pandashan modified and what TrinityCore built. Unfortunately, finding that legacy version would be highly improbable.

**Comment by Kittnz** [comment]
@Epicurus4  I'v been trying add from around https://github.com/TrinityCore/TrinityCore/commits/4.3.4?page=149

Check it out, i'v added a few of them. Some are allready added to the core and are not. I'm sure we could do it together tho.

https://github.com/MistCore/MistCore/commit/f4bfce7cd9e99a1cba1ab12d89803fdf2294b900
Last one i added. That's how close i got.

**Comment by Epicurus4** [comment]
@Kittnz If you're developing on Linux, I recommend a program called "Meld". It features side-by-side diff views of up to three projects. It helps make mergers of a project this large so much more manageable.

My project is not Blizzlike; there are a lot of custom additions to the Core, DBCs, client and database.  MistCore (BloodCore 5.0.5) has not worked too well in accepting my modifications (the core starts but generates massive lag when I try to learn a custom spell, or enter a custom zone, etc), whereas TrinityCore 4.3.4 runs just fine with them. I'm considering moving to 5.1.0, or at the very least testing it out. Worst case scenario, I'll just revert back to Cataclysm.

If I do stick with 5.0.5, I'll collaborate my mergers via pull requests.
